import pioneer_sdk
import time

drone = pioneer_sdk.Pioneer()

# first point
drone.arm()
drone.takeoff()
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, 0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 4, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, -0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, 0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, -3, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, -0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, 0.7, 0)
time.sleep(5)
# second point
drone.go_to_local_point_body_fixed(0, 4, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(1, 0, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, -0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, 0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(-1, 0, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, -3, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, -0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, 0.7, 0)
time.sleep(5)
# third point
drone.go_to_local_point_body_fixed(0, 4, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(1.5, 0, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, -0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, 0.7, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(-1.5, 0, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, -3, 0, 0)
time.sleep(5)
drone.go_to_local_point_body_fixed(0, 0, -0.7, 0)
time.sleep(5)
drone.land()
time.sleep(5)
drone.disarm()